### ISSUE TITLE
RechercheActivity / TrajetsActivity

### ISSUE THREAD

**Issue by NeoRyu** [Kr0uK/AppResAvion#9]
Le bouton RECHERCHER sur RechercheActivity peut être cliqué même si aucune données n'est insérée.
La page trajet effectuant une recherche avec 3 valeurs (la date aller-retour n'etant pas implémentée, on peut supprimer par ailleurs la visibilité du checkbox en le declarant a false pour etre sur), la page plante, mais fait aussi planter l'appli même en cas de retour en arrière.

Solution : 
Dans la page TrajetsActivity, avant toute requête, vérifier si les Strings equals not null, sinon passer des valeurs par defaut (pas top) ou changer la requete plutot pour afficher les données globales (lourd mais il avait qu'a pas faire le con hahaha)

**Comment by bigwanjeog** [comment]
Done
